!!com.compuware.ispw.wzzms.models.IspwRoot
ispwApplication:
  application: AXJ1
  encryptionProtocol: None
  host: CWCC.compuware.com
  hostCodePage: '1047'
  pathMappings:
  - path: \AMAC
    types:
    - fileExtension: amac
      ispwType: AMAC
  - path: \ASM
    types:
    - fileExtension: asm
      ispwType: ASM
  - path: \C
    types:
    - fileExtension: c
      ispwType: C
  - path: \CLST
    types:
    - fileExtension: clst
      ispwType: CLST
  - path: \COB
    types:
    - fileExtension: cbl
      ispwType: COB
  - path: \COPY
    types:
    - fileExtension: cpy
      ispwType: COPY
  - path: \H
    types:
    - fileExtension: h
      ispwType: H
  - path: \INCL
    types:
    - fileExtension: incl
      ispwType: INCL
  - path: \JOB
    types:
    - fileExtension: jcl
      ispwType: JOB
  - path: \PKG
    types:
    - fileExtension: srx
      ispwType: PKG
  - path: \PK1
    types:
    - fileExtension: txt
      ispwType: PK1
  - path: \PLAN
    types:
    - fileExtension: plan
      ispwType: PLAN
  - path: \PLI
    types:
    - fileExtension: pli
      ispwType: PLI
  - path: \PL1
    types:
    - fileExtension: txt
      ispwType: PL1
  - path: \PPT
    types:
    - fileExtension: PPTX
      ispwType: PPT
  - path: \PRC
    types:
    - fileExtension: prc
      ispwType: PRC
  - path: \PREF
    types:
    - fileExtension: prefs
      ispwType: PREF
  - path: \PRJT
    types:
    - fileExtension: project
      ispwType: PRJT
  - path: \PRM
    types:
    - fileExtension: prm
      ispwType: PRM
  - path: \PROC
    types:
    - fileExtension: proc
      ispwType: PROC
  - path: \PROP
    types:
    - fileExtension: properties
      ispwType: PROP
  - path: \PSB
    types:
    - fileExtension: psb
      ispwType: PSB
  - path: \PSUB
    types:
    - fileExtension: psub
      ispwType: PSUB
  - path: \PWS
    types:
    - fileExtension: asm
      ispwType: PWS
  - path: \REFL
    types:
    - fileExtension: ref
      ispwType: REFL
  - path: \REXE
    types:
    - fileExtension: rexe
      ispwType: REXE
  - path: \REXI
    types:
    - fileExtension: rex
      ispwType: REXI
  - path: \REXL
    types:
    - fileExtension: lst
      ispwType: REXL
  - path: \REXX
    types:
    - fileExtension: rex
      ispwType: REXX
  - path: \RSLT
    types:
    - fileExtension: result
      ispwType: RSLT
  - path: \RWTR
    types:
    - fileExtension: cbl
      ispwType: RWTR
  - path: \SAMP
    types:
    - fileExtension: samp
      ispwType: SAMP
  - path: \SCEN
    types:
    - fileExtension: testscenario
      ispwType: SCEN
  - path: \SCHD
    types:
    - fileExtension: schd
      ispwType: SCHD
  - path: \SCR
    types:
    - fileExtension: SCR
      ispwType: SCR
  - path: \SKEL
    types:
    - fileExtension: skel
      ispwType: SKEL
  - path: \SLST
    types:
    - fileExtension: lst
      ispwType: SLST
  - path: \SRB
    types:
    - fileExtension: srb
      ispwType: SRB
  - path: \SRC
    types:
    - fileExtension: src
      ispwType: SRC
  - path: \SRO
    types:
    - fileExtension: cbl
      ispwType: SRO
  - path: \SRP
    types:
    - fileExtension: cbl
      ispwType: SRP
  - path: \SRPC
    types:
    - fileExtension: txt
      ispwType: SRPC
  - path: \SRX
    types:
    - fileExtension: srx
      ispwType: SRX
  - path: \STUB
    types:
    - fileExtension: stub
      ispwType: STUB
  - path: \SUIT
    types:
    - fileExtension: testsuite
      ispwType: SUIT
  - path: \SYSL
    types:
    - fileExtension: sysl
      ispwType: SYSL
  - path: \TABL
    types:
    - fileExtension: tabl
      ispwType: TABL
  - path: \TARC
    types:
    - fileExtension: archive
      ispwType: TARC
  - path: \TEXT
    types:
    - fileExtension: txt
      ispwType: TEXT
  - path: \TINT
    types:
    - fileExtension: interface
      ispwType: TINT
  - path: \TJCL
    types:
    - fileExtension: tjcl
      ispwType: TJCL
  - path: \TLST
    types:
    - fileExtension: listructure
      ispwType: TLST
  - path: \TOTT
    types:
    - fileExtension: tott
      ispwType: TOTT
  - path: \TPRF
    types:
    - fileExtension: prefs
      ispwType: TPRF
  - path: \TPRJ
    types:
    - fileExtension: project
      ispwType: TPRJ
  - path: \TRSL
    types:
    - fileExtension: result
      ispwType: TRSL
  - path: \TRV
    types:
    - fileExtension: csv
      ispwType: TRV
  - path: \TSCN
    types:
    - fileExtension: testscenario
      ispwType: TSCN
  - path: \TSTB
    types:
    - fileExtension: stub
      ispwType: TSTB
  - path: \TSUI
    types:
    - fileExtension: testsuite
      ispwType: TSUI
  - path: \TTT
    types:
    - fileExtension: ttt
      ispwType: TTT
  - path: \UNLK
    types:
    - fileExtension: unlk
      ispwType: UNLK
  - path: \V02
    types:
    - fileExtension: v02
      ispwType: V02
  - path: \WAI
    types:
    - fileExtension: cbl
      ispwType: WAI
  - path: \WDLG
    types:
    - fileExtension: wdlg
      ispwType: WDLG
  - path: \WORD
    types:
    - fileExtension: docx
      ispwType: WORD
  - path: \WRPT
    types:
    - fileExtension: wrpt
      ispwType: WRPT
  - path: \WWW
    types:
    - fileExtension: www
      ispwType: WWW
  - path: \XLRC
    types:
    - fileExtension: xlrc
      ispwType: XLRC
  - path: \XLSX
    types:
    - fileExtension: XLSX
      ispwType: XLSX
  - path: \XML
    types:
    - fileExtension: xml
      ispwType: XML
  - path: \ZIP
    types:
    - fileExtension: zip
      ispwType: ZIP
  port: 16196
  readWriteTimeout: 0
  stream: FTSDEMO
